### ISSUE TITLE
Cortex Operational Dashboards issues

### ISSUE THREAD

**Issue by chodankarcc** [looker-open-source/block-cortex-sap#21]
Team, We have had downloaded 'Cortex Data Foundation for SAP - Operational Dashboards' from Looker Marketplace and it was working fine. Today when we were unable to update BQ dataset name. We found that 'Cortex Data Foundation for SAP - Operational Dashboards' is no more on Looker Marketplace to install. Can you please check on this?

**Comment by benschuler** [comment]
Hi @chodankarcc, the Looker dashboards are no longer maintained on Looker marketplace, instead you can install the blocks manually via the Git URL ([instructions can be found here](https://cloud.google.com/looker/docs/marketplace#installing_a_tool_from_a_git_url)). You will need to provide the URL of this repository, along with the commit SHA of the version that you'd like to install ([here is the list of our releases in this repository](https://github.com/looker-open-source/block-cortex-sap/releases/)). Please let us know if you are facing any issues with this installation method.

After installation, make sure that all of the required user attributes that are [listed in the README file](https://github.com/looker-open-source/block-cortex-sap#required-customizations) are maintained in your Looker instance as well.

**Comment by benschuler** [comment]
Closing this issue as resolved. If you have any further questions, feel free to raise a new issue here with the specific details.
