### ISSUE TITLE
LookML error: "Model Not Found" when opening the dashboards

### ISSUE THREAD

**Issue by mccruz24** [looker-open-source/block-cortex-sap#31]
Hello! I set up the Cortex SAP Block in our Looker Project. I have added  the correct values in manifest and added the user attributes need for this block. But when I open the dashboard, all the charts is getting LookML Error. I'm not sure what's causing the error tho.

Thanks! 

<img width="772" alt="image" src="https://github.com/looker-open-source/block-cortex-sap/assets/132902361/634bc1d5-2b83-4401-aea9-3a81ddfaa8dd">

**Comment by benschuler** [comment]
Hi @mcruzhkm , can you please share how you installed this block? Were you using our repository as an external Git URL on the marketplace (https://cloud.google.com/looker/docs/marketplace#installing_a_tool_from_a_git_url) or did you clone the code into your own repository first and then used that repository as a source for the LookML coding?

Also, can you try looking at your Looker projects to see if the installation is missing a model configuration? See this link for details on how to properly configure a model for a project: https://cloud.google.com/looker/docs/generating-a-model#when_you_need_to_configure_models

Another thing you can check is whether your user needs extra permission to work with the new model. Depending on your role and default setup of the Looker instance, this might be required before you can use it: https://cloud.google.com/looker/docs/admin-panel-users-roles#model_sets

Please let us know if all of the above did not help resolve the issue, in which case we would need to dig deeper into your actual configuration.

**Comment by benschuler** [comment]
Hi @mcruzhkm , are you still facing any issues here or were the steps suggested above helpful in getting it resolved? Please let me know if there is anything else we can help you with, otherwise I'll be closing this issue as completed.

**Comment by mccruz24** [comment]
Hello @benschuler! Apparently the foundation CORTEX_REPORTING views doesnt have the views that Looker version is using. So we're currently updating the views and tables we have in BQ. Once done, we expect that the dashboards, explore and views in Looker would work fine. Thanks!

**Comment by benschuler** [comment]
Okay, thanks for letting us know. I'll close this one then, and if after your update you experience any issues please feel free to raise a new one.
