### ISSUE TITLE
Deployed Demand Sensing Dataset but unable to see data in Looker

### ISSUE THREAD

**Issue by Gururaja12345** [looker-open-source/block-cortex-sap#32]
HI

I have deployed Demand sensing test data from SAP and i am not able to see data in Looker Dashboard.
Please find the below Input details which i deployed :

Forecast Horizon (weeks) :13
Content Window (weeks): 52
Model Training Budget (hours): 1
Deploy Test data : Yes
Mandt Client : 900

Could someone help me why i am unable to see data in Looker Dashboard for Demand sensing.

**Comment by benschuler** [comment]
Hi @Gururaja12345 , 

This repository contains the Looker dashboards for the operational reporting on SAP data. If you'd like to use our demand sensing dashboards, please deploy the code that can be found in this repository as well: https://github.com/looker-open-source/block-cortex-demand-sensing

If you are still seeing issues with the new dashboards, please raise a new issue over there so we can properly track it and help you get it resolved.

**Comment by Gururaja12345** [comment]
I have deployed Demand sensing and i have data set. Please find the attachement and i cannot see any data in Looker

![Demand sensing Data set](https://github.com/looker-open-source/block-cortex-sap/assets/135985089/7365c5d4-f1f6-44b9-b110-e21bef59a2d3)
![Demand sensing](https://github.com/looker-open-source/block-cortex-sap/assets/135985089/770092f8-7a41-46fb-84e5-60e616b08dcd)

**Comment by Gururaja12345** [comment]
Hi Benschuler,

You want me to Redeploy once again for Demand sensing with the below Parameters.

Forecast Horizon (weeks) :13
Content Window (weeks): 52
Model Training Budget (hours): 1
Deploy Test data : Yes
Mandt Client : 900

Could you please confirm as i already deployed data but i cannot see data i Looker 
![Demand sensing Data set not displaying ](https://github.com/looker-open-source/block-cortex-sap/assets/135985089/e996d8da-807b-483e-87a8-8b31b9dbff6c)

**Comment by benschuler** [comment]
Let's stick to the one issue that is still open, otherwise we are losing context --> https://github.com/looker-open-source/block-cortex-sap/issues/33
